name: tw_weather
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  package_info_plus: ^1.3.0
  get_storage: ^2.0.3
  dio: ^4.0.4
  decorated_icon: ^1.2.1
  simple_shadow: ^0.2.0
  flutter_svg: ^1.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  lottie: ^1.2.1
  get: 4.6.1
  location: ^4.3.0
  geocoding: ^2.0.2
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/image/

